/**
 * State feature key (prefix of action name)
 */
export const FeatureKey = {
    COUNTER: "COUNTER",
    USER: "USER",
    WEB: "WEB",
    PARTMASTER: "PARTMASTER",
    BILLOFMATERIALS: "BILLOFMATERIALS",
    FUNCTIONSMASTER: "FUNCTIONSMASTER",
    SHIKYUGOODSRECEIVE: "SHIKYUGOODSRECEIVE",
    SHIKEYUFROM: "SHIKEYFROM",
    PROCESSMASTER: "PROCESSMASTER",
    STOCKHISTORY: "STOCKHISTORY",
    SHIPPINGRESULT: "SHIPPINGRESULT",
    SHIPPINGTO: "SHIPPINGTO",
    PROCESSCOMPLETIONRESULT: "PROCESSCOMPLETIONRESULT",
    MODIFIEDREASONMASTER: "MODIFIEDREASONMASTER",
    STOCKRESULTMODIFICATION: "STOCKRESULTMODIFICATION",
    OPERATIONCALENDAR: "OPERATIONCALENDAR",
    EVENT: "EVENT"
} as const;